[package]
name = "opensentinel-server"
version = "1.0.0"
edition = "2021"
authors = ["Azanian Eagle <info@azanianeagle.co.za>"]
description = "OpenSentinel high-performance backend server and local ONNX machine learning engine for non-invasive bot detection, engineered by Azanian Eagle."
license = "MIT"
repository = "https://github.com/Azanian-Eagle/OpenSentinel"
homepage = "https://github.com/Azanian-Eagle/OpenSentinel"
documentation = "https://github.com/Azanian-Eagle/OpenSentinel#readme"
readme = "README.md"
keywords = ["captcha", "security", "bot-detection", "privacy", "anti-bot"]
categories = ["web-programming", "network-programming", "science"]

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"
log = "0.4"
ndarray = "0.17.2"
actix-cors = "0.7.1"
base64 = "0.22.1"
sha2 = "0.11.0"
reqwest = { version = "0.12.0", default-features = false, features = ["rustls-tls-native-roots", "json"] }
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros", "sync"] }
hex = "0.4.3"
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand = "0.10.1"
rand_core = "0.10.1"
aes-gcm = "0.10.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
link-cplusplus = "1.0.12"

[target.'cfg(all(target_os = "windows", target_env = "msvc"))'.dependencies]
ort = { version = "2.0.0-rc.12", features = ["download-binaries"] }

[target.'cfg(all(target_os = "macos", target_arch = "x86_64"))'.dependencies]
ort = { version = "2.0.0-rc.12", default-features = false, features = ["std", "ndarray", "tracing", "tls-native", "copy-dylibs", "api-27", "load-dynamic"] }

[target.'cfg(all(not(target_os = "windows"), not(all(target_os = "macos", target_arch = "x86_64"))))'.dependencies]
ort = { version = "2.0.0-rc.12", features = ["download-binaries"] }
