apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensentinel.fullname" . }}-service
  labels:
    app: {{ include "opensentinel.name" . }}
    helm.sh/chart: {{ include "opensentinel.chart" . }}
    app.kubernetes.io/name: {{ include "opensentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ include "opensentinel.name" . }}
    app.kubernetes.io/name: {{ include "opensentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}