apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "opensentinel.fullname" . }}
  labels:
    {{- include "opensentinel.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "opensentinel.name" . }}
      app.kubernetes.io/name: {{ include "opensentinel.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
